version: "2.2"

services:
 cineweb-portal:
  container_name: cineweb-movies-api
  image: public.ecr.aws/m7x6b7n4/cineweb-movies-api:latest
  environment:
  - PORT=80
  ports:
  - 80:80
  build:
   context: .
   dockerfile: Dockerfile